version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: db-bienes-raices
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_PASSWORD=pass_bienesraices
      - MYSQL_USER=user_bienesraices
      - MYSQL_DATABASE=bienesraices
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local